services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: polla
      POSTGRES_PASSWORD: polla_dev
      POSTGRES_DB: the_big_polla
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
